### PR TITLE
PA Counties that have no paper trail-more detailed

### PR DESCRIPTION
**Pull request by josephplattenberger**
info seperated by tabs

### CODE REVIEW

**Comment by HelloKitty** [comment]
Hi, I'll go ahead and merge and reorganize abit after that.

One thing though, do you have any source for claiming that there is no paper trail in PA? Also, PA is already listed as a state on our radar. Are you implying we should change our strategy against PA?

**Comment by HelloKitty** [comment]
Or are these just a subset of PA counties that have no paper trail?

**Comment by josephplattenberger** [comment]
@HelloKitty these are a subset of counties w/o a paper trail. but they include more detail than the original list. all source is pulled from: https://www.verifiedvoting.org/verifier/
website details exactly the equipment each county uses. no paper trail = "without VVPAT"

**Comment by HelloKitty** [comment]
Alright, I'll merge and reorganize shortly. Then I'll add a section about this in the main Readme.

**Pull request merged**
