### PR TITLE
Create GeorgiaCounties.txt

### PR DESCRIPTION
**Pull request by josephplattenberger**

### CODE REVIEW

**Comment by HelloKitty** [comment]
@josephplattenberger I'm not against adding Georgia but right now we target Smartmantic and Sequoia machines and Soros connected companies.

Do you believe Georgia is using such machines?

**Comment by josephplattenberger** [comment]
@HelloKitty The entire state of georgia is using electronic voting machines with no paper trail. link: https://www.verifiedvoting.org/verifier/#year/2016/state/13
This was one of the states that was not consistent with polling during the democratic primary. We need to focus on all voting machines that do not have a paper trail. We can use the website linked above to determine which counties use machines without paper trails.

**Comment by josephplattenberger** [comment]
@HelloKitty by Smartmatics own submission they have revealed none of their technology with be used for the upcoming 2016 US election: http://www.smartmatic.com/case-studies/article/facts-about-smartmatic/

However, Dominion Voting and H.I.G. Capital (Hart Intercivic) are two other voting machine companies which were revealed thru the Guciffer 2.0 hacks to have made substantial donations to the Clinton Foundation. https://guccifer2.files.wordpress.com/2016/06/clinton-foundation-donors-25k.xlsx

We must demand that ALL machines either produce paper trails or paper ballots must be provided.

**Comment by HelloKitty** [comment]
@josephplattenberger Smartmatic and Sequoia should be treated as one. Places are using Sequoia brand machines.

I agree we need to demand a paper trail and to switch to paper. James on the subreddit is making decisions such as that. I personally aggregate the data and try to manage the community contributions.

If we want to go full-scale against states that don't use paper trails we need to atleast knock out the places that use Sequoia.

**Comment by HelloKitty** [comment]
I'll contact James and ask if we should create a separate section for non-paper trail or potentially problematic states.

**Comment by josephplattenberger** [comment]
@HelloKitty ok. I tried to let him know that Soros machines were not being used in this election. I honestly believe that we should reduce our list to only swing states that have machines without a paper trail. We can even reduce the counties down using this website https://www.verifiedvoting.org/verifier which shows what equipment is used in each county.

**Comment by HelloKitty** [comment]
@josephplattenberger Yea, I've been trying to get him to change the focus from Smartmatic to Sequoia/Smartmatic. I think I'm going to take action on that myself on the Github now.

I'm convinced that we should focus swing states, I'm convinced we need a paper trail in any state with electronic machines but the direction of the movement isn't up to me. I'm just an aggregator and wiki manager more or less.

**Comment by josephplattenberger** [comment]
@HelloKitty So literally the entire state of georgia is not using a paper trail. all 159 counties.. I might need to find a faster way of pulling data from this site: https://www.verifiedvoting.org/verifier/#year/2016/state/13

**Comment by Centipede86** [comment]
Centipede from Georgia (Whitfield county)... Is there any grunt work to do? I can help.

**Comment by Centipede86** [comment]
Oh... I probably should have said @HelloKitty... Helper from Georgia if needed... I don't have any code or scraping experience, but I can manually collect numbers or whatever...

**Comment by ladynai** [comment]
@Hello, I just joined to help. Great effort. Thank you. I haven't know what to do about this Voter Integrity issue. Sorry this is so long, but I've a few suggestions to take back to the organizational heads.

I saw this ballot stuffing - of paper ballots - and I know Trump camp has asked for poll watchers. In CA, we are allowed one per side. If someone leaves for a bathroom break, just look how many ballots they stuff when no one is looking?! https://twitter.com/KevJames91/status/789582681478533120

I think they are also pushing back on Trump poll watchers as dangerous thugs, as if. Anyway, I thought drones outside the crucial polls. To check out the suspicious licenses of auction cars and run those plates somehow. Project Veritas said the buses are too obvious and they use cars from auctions, registered to a business. Because Clinton Cash talks about their intimidation in foreign elections - firebombing, etc. 90% wins. Technology and surprise would catch any tactics they use or repeat voters, buses, Veritas videos show car auctions to businesses for registration hiding. 

This is what we're up against. They fight (read: cheat) to win. 

StopTheSteal.org (Roger Stone) and Judicial Watch have attorneys - I think it's a good idea to ask if requests should be in writing with proof of receipt? When I've look up counties for people with ballot issues, there is always an email address and physical address, too. Phones, they can take off the hook or claim not receiving an email. It isn't legal notification. Legally, we need written requests with the signature receipt cards. I know that's more work, but millions would help with research and printing letters and pay for $6 for the letter to go out. It could even say: 400 people called and this is to confirm our request that this-and-that statute is applied. 

I would prep this like it's going to court for an emergency injunction. I've seen judges refuse to believe any correspondence without those green postcard proofs that someone signed for a letter. 

These people know they aren't accountable and will cheat like that video montage. They are without morals. Undercover video of ballot stuffers from security cameras in PA and other states is now on twitter. They wait for a lull and the whole place is stuffing the boxes! And what names are the putting on all those ballots. Ugh. I couldn't believe it. But there is no ID in VA if you register online. Getting an absentee ballot (I could not request without being a resident). But couldn't each state have someone show the loopholes in registering so we can stop it. The 19 dead people in VA were only caught when they mailed an acknowledgement to the house and family caught it. However, the Gov. refused the money/permission to investigate the other counties. Only IN, where Pence can help, has State Troopers investigating their fraud - widespread. 

Could we harness people to compare Social Security Death Index and citizenship Indexes with new voter rolls? I mean, the honor system for illegals/felons not registering yields millions of frauds there, too.

 I'd be willing to research physical address and email. If we put up a WeSearchR or GoFundMe for buying the voter rolls and systematically do the job that they obviously won't OK in rigged govt, great. 

Corruption will only move with a judge's order. Like Judicial Watch with FOIA. Unless jail is on the table, they won't budge. Even coordinating with Judicial Watch on what is needed would be a great way to go IMO.

**Comment by josephplattenberger** [comment]
@ladynai that video of people stuffing the ballot boxes is from Russia. But I do think one of the biggest counters to voter fraud will be poll workers and election observers. http://www.youtube.com/watch?v=uPO1swQVMoc&t=1m38s

**Pull request closed without merging**
