### PR TITLE
Create EriePA2020161144AM.txt

### PR DESCRIPTION
**Pull request by triton11**
Things went more or less according to plan. MAGA.

### CODE REVIEW

**Comment by abhisuri97** [comment]
Can you make this in JavaScript?

**Comment by HelloKitty** [comment]
Good work, thank you for your contribution.

Sorry it took so long to much.

**Comment by HelloKitty** [comment]
@abhisuri97 It seems like @triton11 took your comment to heart. I realize it was just in jest but he ended up making another PR with a .js extension. Sooooo yea, may not be beneficial to the cause.

**Comment by HelloKitty** [comment]
@triton11 @abhisuri97 I've reverted this PR. I didn't realize trolls and CTR were already on top of this.

You are now permanently banned from any PRs.

**Pull request merged**
